[env:base]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
monitor_speed = 115200

[env:blink]
extends = env:base
build_src_filter = +<scripts/blink.cpp>

[env:test_mic]
extends = env:base
build_src_filter = +<scripts/test_mic.cpp> +<sensors/mic_sensor.cpp>

[env:test_button]
extends = env:base
build_src_filter = +<scripts/test_button.cpp> +<sensors/button_sensor.cpp>

[env:test_mqtt]
extends = env:base
build_src_filter = +<scripts/test_mqtt.cpp> +<comms/mqtt_client.cpp>
lib_deps=
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.4.2

[env:test_hall]
extends = env:base
build_src_filter = +<scripts/test_hall.cpp> +<sensors/hall_sensor.cpp>

[env:test_record]
extends = env:base
build_src_filter = +<scripts/test_record.cpp> +<sensors/mic_sensor.cpp> +<sensors/button_sensor.cpp> +<comms/mqtt_client.cpp>
lib_deps=
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.4.2

[env:main]
extends = env:base
build_src_filter = +<main.cpp> +<sensors/mic_sensor.cpp> +<sensors/button_sensor.cpp> +<sensors/hall_sensor.cpp> +<comms/mqtt_client.cpp>
lib_deps=
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.4.2