[env:base]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
monitor_speed = 115200

[env:blink]
extends = env:base
build_src_filter = +<scripts/blink.cpp>

[env:test_mic]
extends = env:base
build_src_filter = +<scripts/test_mic.cpp> +<sensors/mic_sensor.cpp>
